ci: upgrade build, lint, pre-commit and pre-push scripts

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,1 +1,20 @@
-bun run build
+bun run format
+if [ $? -ne 0 ]; then
+  echo "\033[0;31mFormatting failed. Push aborted.\033[0m"
+  exit 1
+fi
+if [ $? -eq 0 ]; then
+  echo "\033[0;32mFormatting passed.\033[0m"
+fi
+
+npm run build
+if [ $? -ne 0 ]; then
+  echo "\033[0;31mBuild process failed. Push aborted.\033[0m"
+  exit 1
+fi
+if [ $? -eq 0 ]; then
+  echo "\033[0;32mBuild process passed.\033[0m"
+fi
+
+BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
+echo "\033[0;35mAll checks passed. Pushing to remote branch: '$BRANCH_NAME'.\033[0m"
